---
name: "module3_task0"
run-name: module3_task0

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches:
      - main

jobs:
  build:
    name: hugoRun
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build the content
        run: make build
