---
name: "module3_task3"
run-name: module3_task3

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - main

jobs:
  deps:
    name: dependencies
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./module3_task3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: ./setup.sh

      - name: Build web
        run: make build

      - name: Unit tests
        run: make unit-tests

      - name: Integration tests
        run: make integration-tests

      - name: Test both (Integration tests / unit tests)
        run: make test

      - name: Run Linter
        run: make lint

      - name: Validate html files
        run: make validate

      - name: Run the web aplication
        run: make run

      - name: Stop aplication
        run: make stop

      - name: Clean files
        run: make clean

      - name: Create package
        run: make build && make package

      - name: Upload package to the principal branch
        uses: actions/upload-artifact@v3
        with:
          name: awesome-website.zip
          path: ./module3_task3/awesome-website.zip

      - name: "1.0.0"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./module3_task3/awesome-website.zip
            ./module3_task3/DEPLOY.md
          body_path: ./module3_task3/DEPLOY.md
