---
name: "module3_task5"
run-name: module3_task5

on:
  schedule:
    - cron: "0 1 * * *"
  pull_request:
  push:
    branches:
      - main
    tags: 1.0.0

jobs:
  deps:
    name: dependencies
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./module3_task5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: ./setup.sh

      - name: Build web
        run: make build

      - name: Unit tests
        run: make unit-tests

      - name: Integration tests
        run: make integration-tests

      - name: Test both (Integration tests / unit tests)
        run: make test

      - name: Run Linter
        run: make lint

      - name: Validate html files
        run: make validate

      - name: Run the web aplication
        run: make run

      - name: Stop aplication
        run: make stop

      - name: Clean files
        run: make clean

      - name: Create package
        run: make build && make package

      - name: Upload package to the principal branch
        uses: actions/upload-artifact@v3
        with:
          name: awesome-website.zip
          path: ./module3_task5/awesome-website.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./module3_task5/awesome-website.zip
            ./module3_task5/DEPLOY.md
          tag_name: 1.0.0
          body_path: ./module3_task5/DEPLOY.md

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
