---
name: release_drafter
run-name: release_drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]


permissions:
  contents: read

jobs:
  update_release_draft:
    name: release_drafter
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
